services:
  mongo-1:
    image: mongo:7.0.17-rc1-jammy
    container_name: mongo-1
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=abc123!
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - mongo-net

  express:
    image: node:latest
    container_name: express-app
    environment:
      - MONGO_URI=mongodb://root:abc123!@mongo-1:27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=mongo-1
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=abc123!
      - ME_CONFIG_OPTIONS_EDITORTHEME=default
    working_dir: /usr/src/app
    volumes:
      - ./express-app:/usr/src/app
      - ./data-transfer:/data-transfer
    ports:
      - 28203:8081
    networks:
      - mongo-net
    depends_on:
      - mongo-1
    command: "npm start"

volumes:
  mongo-data:

networks:
  mongo-net:
    driver: bridge